apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pagamento
  template:
    metadata:
      labels:
        app: ms-pagamento
    spec:
      serviceAccountName: irsasecrets
      containers:
        - name: ms-pagamento
          image: 851725345801.dkr.ecr.us-east-1.amazonaws.com/ms-pagamento:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 120
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: ms-pagamento-configmap
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-pagamento
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-pagamento
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-pagamento-configmap
data:
  PAYMENT_API_URL: 'http://sistema-de-pagamento:3000/payment'
  AWS_SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:851725345801:payment-status-topic"
